version: "3"
services:
  app:
    container_name: product-service
    build: ./ 
    networks: 
      product-review-service
	restart: always
    ports:
      - "3001:3001"
    external-links:
      - product-review-service
networks: 
  product-review-service